services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
        - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  hoverfly:
    container_name: hoverfly
    image: spectolabs/hoverfly:v2.0.0
    command:
    - "-webserver"
    - "-response-body-files-path=/hoverfly_app/response"
    - "-import=/hoverfly_app/simulations/recommend.simulation.json"
    volumes:
      - "$PWD/hoverfly:/hoverfly_app:ro"
    ports:
      - "8500:8500"
      - "8888:8888"

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
